CREATE TABLE users(id TEXT PRIMARY KEY,key_hash TEXT UNIQUE NOT NULL,active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)),expires_at INTEGER NOT NULL);
CREATE TABLE consent_sessions(id TEXT PRIMARY KEY,request_url TEXT NOT NULL,expires_at INTEGER NOT NULL);
