import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { randomBytes, createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import { Client, StreamableHTTPClientTransport } from '@modelcontextprotocol/client';
import { execFileSync } from 'node:child_process';

const origin=process.env.TEST_ORIGIN||'http://localhost:8794';
const keyPath=process.env.TEST_KEY_FILE||'.local-data/auth/researcher.key';
const checks=[];const ok=name=>checks.push(name);
const request=(path,options={})=>fetch(`${origin}${path}`,{...options,signal:AbortSignal.timeout(15000)});
const jsonPost=data=>({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
const post=data=>({method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(data)});
assert.equal((await request('/health')).status,200);ok('health');
assert.equal((await request('/mcp',jsonPost({jsonrpc:'2.0',id:1,method:'tools/list'}))).status,401);ok('unauthenticated_rejected');
assert.equal((await request('/mcp',{...jsonPost({}),headers:{'Content-Type':'application/json',Origin:'https://untrusted.example'}})).status,403);ok('foreign_origin_rejected');
assert.equal((await request('/oauth/register',{method:'POST',body:'x'.repeat(17000)})).status,413);ok('oversized_body_rejected');
const register=await request('/oauth/register',jsonPost({client_name:'DigitalBrain automated acceptance',redirect_uris:['http://127.0.0.1:18931/callback'],token_endpoint_auth_method:'none',grant_types:['authorization_code','refresh_token'],response_types:['code']}));
assert.equal(register.status,201);const {client_id}=await register.json();ok('oauth_registration');
const verifier=randomBytes(32).toString('base64url');
const params=new URLSearchParams({client_id,redirect_uri:'http://127.0.0.1:18931/callback',response_type:'code',scope:'research:read',state:randomBytes(16).toString('hex'),code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256',resource:`${origin}/mcp`});
const bad=new URLSearchParams(params);bad.set('resource','https://wrong.example/mcp');
assert.equal((await request(`/authorize?${bad}`)).status,400);ok('wrong_resource_rejected');
const badRedirect=new URLSearchParams(params);badRedirect.set('redirect_uri','https://untrusted.example/callback');
assert.equal((await request(`/authorize?${badRedirect}`)).status,400);ok('unregistered_redirect_rejected');
const page=await request(`/authorize?${params}`);assert.equal(page.status,200);
const html=await page.text();const session=html.match(/name="session" value="([^"]+)"/)?.[1];assert.ok(session);
const cookie=page.headers.get('set-cookie').split(';')[0];
const consent=post({session,key:readFileSync(keyPath,'utf8').trim(),consent:'yes'});
const accepted=await request('/authorize',{...consent,headers:{...consent.headers,Origin:origin,Cookie:cookie},redirect:'manual'});assert.equal(accepted.status,302);
const redirect=new URL(accepted.headers.get('location'));assert.equal(redirect.searchParams.get('state'),params.get('state'));ok('oauth_consent');
const tokenRequest={grant_type:'authorization_code',client_id,code:redirect.searchParams.get('code'),redirect_uri:params.get('redirect_uri'),code_verifier:verifier,resource:`${origin}/mcp`};
const tokenResponse=await request('/oauth/token',post(tokenRequest));assert.equal(tokenResponse.status,200);let tokens=await tokenResponse.json();assert.ok(tokens.access_token);ok('pkce_token_exchange');
mkdirSync('artifacts',{recursive:true});
const keyFile='artifacts/oauth-access.key';writeFileSync(keyFile,tokens.access_token,{mode:0o600});
execFileSync(process.execPath,['--experimental-strip-types','scripts/validate.ts'],{stdio:'inherit',env:{...process.env,TEST_ORIGIN:origin,TEST_KEY_FILE:keyFile,REPORT_PATH:'artifacts/gateway-validation.json',TEST_MUTATIONS:'0'}});
ok('gateway_to_lab_six_tools_and_source_fidelity');
const refresh=await request('/oauth/token',post({grant_type:'refresh_token',client_id,refresh_token:tokens.refresh_token,resource:`${origin}/mcp`}));
assert.equal(refresh.status,200);ok('refresh_token');
assert.notEqual((await request('/oauth/token',post(tokenRequest))).status,200);ok('authorization_code_replay_rejected');
const report={at:new Date().toISOString(),checks,passed:checks.length};writeFileSync('artifacts/oauth-validation.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
